### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by jridgway** [botandrose/refinerycms-ckeditor#1]
I'm unable to get this working on Heroku. I get two errors when ckeditor.js tries to load kama/editor.css and the lang/en.js. I have following config if it helps:

``` ruby
if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  # Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  Bundler.require(:default, :assets, Rails.env)
end

config.assets.enabled = true
config.assets.initialize_on_precompile = false
config.serve_static_assets = false
config.assets.compress = true
config.assets.compile = true
config.assets.digest = true
config.assets.js_compressor  = :uglifier
config.assets.css_compressor = :scss
```

**Comment by jridgway** [comment]
I finally fixed this by setting config.assets.digest = false and removing several instances of "filter:;" in skins/kama/ckeditor.css.

**Comment by jridgway** [comment]
I've run into more issues with ckeditor's css. Instead of painstakingly fixing each, I've set config.assets.compress = false. Is there any other way around this, so that I can still compress my assets?

**Comment by botandrose** [comment]
Confirmed. Investigating...

**Comment by botandrose** [comment]
Yep, the digest interferes with ckeditor autodetecting the base path of the ckeditor install, which screws up subsequent script loads. Just released v0.1.1 which fixes this by setting the base path manually before loading ckeditor, so you can turn your digests back on.

Looking into the css errors now. It's parsing the css with sass, which makes no sense...

**Comment by botandrose** [comment]
Ah, sass is also used as the default rails css compressor. So even if a css file doesn't require any other sass functionality, if sass can't parse it, it'll barf when trying to compress. Hmm...

**Comment by botandrose** [comment]
Ended up replacing all the instances of filter:; with filter:none; making the file valid. I'll try to push this fix upstream. In any case, v0.1.2 should get you going. Reopen if not!
