### ISSUE TITLE
about adding plugin 

### ISSUE THREAD

**Issue by purpletianjing** [botandrose/refinerycms-ckeditor#10]
Hi botandrose,
I try to add a plugin to this project, and I did it as CKEditor website [guides.](http://docs.cksource.com/CKEditor_3.x/Tutorials/Timestamp_Plugin) But it didn't display in the web page after I created it and added it to config.js like this: `CKEDITOR.editorConfig = function( config ) {
    CKEDITOR.replace( 'editor1',
        {
            extraPlugins : 'timestamp',
            toolbar :
                [
                    [ 'Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink' ],
                    [ 'Timestamp' ]
                ]
        });
};`

I don't know where is wrong~

**Comment by botandrose** [comment]
Hello. The problem you're having looks like it has nothing to do with this particular project. I suggest asking for help from the maintainer of the timestamp plugin that you're trying to add. Good luck!

**Comment by purpletianjing** [comment]
Thank you! I solve it by myself! It's different from single CKEditor, so I need to add it to ckeditor.js.
