### ISSUE TITLE
Does not work on refinerycms 1.0.9

### ISSUE THREAD

**Issue by jbmk** [botandrose/refinerycms-ckeditor#3]
How to use refinerycms-ckeditor plugin for refinerycms version 1.0.9

**Comment by botandrose** [comment]
Hi @jbmk, this requires refinerycms 2.0.0 or above, as stated in the README. The main reason for this is that there are a lot of javascript and image assets in this gem, so we need the asset pipeline to serve them, and refinerycms 1.x.x is based on Rails 3.0, so no asset pipeline. :(
